# Generated by Django 5.2.7 on 2025-11-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportToken',
            fields=[
                ('token', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('USER', 'User'), ('PROJECT', 'Project'), ('SITE', 'Site')], max_length=10)),
                ('resource_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'export_token',
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='export_toke_resourc_391f43_idx')],
            },
        ),
    ]
