version: "3"

services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    image: techmatters/terraso-backend:${TAG:-latest-dev}
    env_file: .env.ci
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.yml
      service: db

volumes:
  postgresql_data:
