services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    volumes:
      - type: bind
        source: /home/runner/work/terraso-backend/terraso-backend/Data
        target: /app/Data
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.base.yml
      service: db

volumes:
  postgresql_data:
