services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    volumes:
      - type: bind
        source: /home/runner/work/terraso-backend/terraso-backend/Data
        target: /app/Data
      - type: tmpfs
        target: /app/.ruff_cache
        tmpfs:
          size: 100M
    depends_on:
      db:
        condition: service_healthy
      soil-id-db:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.base.yml
      service: db
  
  soil-id-db:
    extends:
      file: docker-compose.base.yml
      service: soil-id-db

volumes:
  postgresql_data:
