version: "3"

services:
  web:
    image: techmatters/terraso_backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python terraso_backend/manage.py runserver 0.0.0.0:${PORT}
    labels:
      org.techmatters.project: terraso_backend
    env_file: .env
    volumes:
      - .:/app:z
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true

  db:
    image: "postgis/postgis:14-master"
    labels:
      org.techmatters.project: terraso_backend
    env_file: .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    hostname: postgres
    environment:
      - POSTGRES_DB=terraso_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
    healthcheck:
      test: pg_isready -U postgres -d terraso_backend
      interval: 3s
      timeout: 5s
      start_period: 3s
      retries: 3

volumes:
  postgresql_data:
