[project]
name = "terraso_backend"
readme = "README.md"
version = "1.0"
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = [
    "boto3==1.42.15",
    "dj-database-url==3.0.1",
    "django==5.2.7",
    "django-cors-headers==4.9.0",
    "django-dirtyfields==1.9.7",
    "django-filter==25.2",
    "django-naomi==0.8",
    "django-oauth-toolkit==3.1.0",
    "django-safedelete==1.4.1",
    "django-ses==4.4.0",
    "django-storages==1.14.6",
    "django-structlog==9.1.1",
    "fiona==1.10.1",
    "gdal==3.11.3",
    "geopandas==1.1.1",
    "graphene-django==3.2.3",
    "gunicorn==23.0.0",
    "httpx==0.28.1",
    "openpyxl==3.1.5",
    "pandas==2.3.3",
    "posthog==7.19.1",
    "prettyconf==2.3.0",
    "psycopg==3.2.10",
    "pyjwt[crypto]==2.10.1",
    "pyproj==3.7.2",
    "python-magic==0.4.27",
    "requests==2.32.5",
    "rules==3.5",
    "sentry-sdk[django]==2.48.0",
    "shapely==2.1.2",
    "soil-id",
]

[dependency-groups]
lint = ["ruff==0.14.10"]
dev = [
    { include-group = "lint" },
    "deepdiff==8.6.1",
    "freezegun==1.5.5",
    "gdown==5.2.0",
    "ipdb==0.13.13",
    "jsonpath-ng==1.7.0",
    "mixer==7.2.2",
    "moto==5.1.19",
    "pre-commit==4.5.1",
    "pytest==9.0.2",
    "pytest-cov==7.0.0",
    "pytest-django==4.11.1",
    "respx==0.22.0",
]

[tool.uv.sources]
soil-id = { url = "https://github.com/techmatters/soil-id-algorithm/archive/refs/tags/2026-07-20.0.zip" }

[tool.uv]
no-binary-package = ["fiona"]
required-version = ">=0.6.0"

[tool.ruff]
exclude = ["migrations"]
line-length = 100
required-version = "==0.14.10"

[tool.ruff.lint.isort]
known-first-party = ["apps"]

[tool.ruff.lint]
extend-select = ["I"]
extend-ignore = ["E203"]
