# Generated by Django 4.2.4 on 2023-08-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE collaboration_membership SET user_role ='collaborator' WHERE user_role='contributor';"
        ),
    ]
