# Generated by Django 4.2.4 on 2023-08-21 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0002_change_contributor_to_collaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
