# Generated by Django 4.2.4 on 2023-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0003_membership_pending_email"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("membership_list", "pending_email"),
                name="unique_pending_collaboration_membership",
            ),
        ),
    ]
