# Generated by Django 4.0.4 on 2022-05-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared_data", "0002_dataentry_size"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dataentry",
            name="shared_data_dataentry_unique_active_slug",
        ),
        migrations.RemoveField(
            model_name="dataentry",
            name="slug",
        ),
        migrations.AlterField(
            model_name="dataentry",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
