# Generated by Django 4.0.6 on 2022-08-18 18:38

import uuid

import django.db.models.deletion
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shared_data", "0004_merge_20220609_1921"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualizationConfig",
            fields=[
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("configuration", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_visualization_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shared_data.dataentry"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visualization Configs",
                "ordering": ["created_at"],
                "get_latest_by": "-created_at",
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
