# Generated by Django 4.1 on 2022-09-26 22:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("shared_data", "0005_visualizationconfig"),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM shared_data_visualizationconfig;"),
        migrations.AddField(
            model_name="visualizationconfig",
            name="title",
            field=models.CharField(
                max_length=128, validators=[apps.core.models.commons.validate_name]
            ),
        ),
        migrations.AddField(
            model_name="visualizationconfig",
            name="group",
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name="visualizationconfig",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visualizations",
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="visualizationconfig",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=250),
        ),
        migrations.AddConstraint(
            model_name="visualizationconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("group_id", "slug"),
                name="shared_data_visualizationconfig_unique_active_slug_by_group",
            ),
        ),
    ]
