# Generated by Django 4.1 on 2022-11-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared_data", "0006_visualizationconfig_title_group_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataentry",
            name="entry_type",
            field=models.CharField(
                choices=[("file", "File"), ("link", "Link")], default="file", max_length=32
            ),
            preserve_default=False,
        ),
    ]
