# Generated by Django 4.1 on 2022-11-03 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared_data", "0006_visualizationconfig_title_group_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataentry",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="visualizationconfig",
            name="data_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visualizations",
                to="shared_data.dataentry",
            ),
        ),
        migrations.AlterField(
            model_name="visualizationconfig",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
