# Generated by Django 4.1.3 on 2022-12-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared_data", "0008_alter_dataentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataentry",
            name="resource_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
