# Generated by Django 4.2.2 on 2023-06-21 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shared_data", "0009_alter_dataentry_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualizationconfig",
            name="mapbox_tileset_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="visualizationconfig",
            name="mapbox_tileset_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("ready", "Ready"), ("failed", "Failed")],
                default="pending",
                max_length=128,
            ),
        ),
    ]
