# Copyright © 2024 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 5.1 on 2024-08-16 19:47

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def update_rows(apps, schema_editor):
    VisualizationConfig = apps.get_model("shared_data", "VisualizationConfig")
    for obj in VisualizationConfig.objects.all():
        obj.readable_id = secrets.token_hex(4)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("shared_data", "0017_visualizationconfig_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="visualizationconfig",
            name="shared_data_visualizationconfig_unique_active_slug_by_owner",
        ),
        migrations.AddField(
            model_name="visualizationconfig",
            name="readable_id",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.RunPython(update_rows),
        migrations.AddConstraint(
            model_name="visualizationconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("owner_object_id", "slug", "readable_id"),
                name="shared_data_visualizationconfig_unique_active_slug_by_owner",
            ),
        ),
    ]
