# Generated by Django 5.2.7 on 2025-11-15 08:52
#
# Drift migration: Captures field changes (deleted_at indexes, ForeignKey updates) that were
# applied to production but never recorded in migrations.
#
# IMPORTANT: This migration is IRREVERSIBLE.
# The forward migration is idempotent and safe - it updates Django's migration state to match
# the actual production database state that has existed since 2022.
#
# Rolling back this migration would:
# - Drop db_index from deleted_at fields (performance regression)
# - Revert created_by ForeignKey on_delete behavior (potential data consistency issues)
#
# Therefore, reverse migration is disabled to prevent accidental production breakage.
#
# STATE CHANGES CAPTURED (commented out to show what Django detected):
#
# migrations.AlterField(
#     model_name='dataentry',
#     name='created_by',
#     field=models.ForeignKey(
#         null=True,
#         on_delete=django.db.models.deletion.DO_NOTHING,
#         to=settings.AUTH_USER_MODEL
#     ),
# ),
#
# migrations.AlterField(
#     model_name='dataentry',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),
#
# migrations.AlterField(
#     model_name='visualizationconfig',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_data', '0018_visualizationconfig_readable_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='dataentry',
                    name='created_by',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='dataentry',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                migrations.AlterField(
                    model_name='visualizationconfig',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
            ],
            database_operations=[
                # Database is already in this state from production, so do nothing
                migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
            ],
        ),
    ]
