# Generated by Django 4.2.2 on 2023-06-06 08:34

import apps.audit_logs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("client_timestamp", models.DateTimeField()),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("READ", "READ"),
                            ("CHANGE", "CHANGE"),
                            ("DELETE", "DELETE"),
                        ],
                        default=apps.audit_logs.models.Events["CREATE"],
                        max_length=10,
                    ),
                ),
                ("resource_id", models.UUIDField()),
                ("resource_json_repr", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "resource_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
