# Copyright © 2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.
# Generated by Django 4.2.2 on 2023-06-07 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.audit_logs.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("client_timestamp", models.DateTimeField()),
                ("user_human_readable", models.CharField(max_length=255)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("READ", "READ"),
                            ("CHANGE", "CHANGE"),
                            ("DELETE", "DELETE"),
                        ],
                        default=apps.audit_logs.models.Events["CREATE"],
                        max_length=50,
                    ),
                ),
                ("resource_id", models.UUIDField()),
                ("resource_json_repr", models.JSONField()),
                ("resource_human_readable", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "resource_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource_content_type", "resource_id"],
                        name="audit_logs__resourc_0ca8cf_idx",
                    )
                ],
            },
        ),
    ]
