# Generated by Django 4.2.1 on 2023-05-09 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="resource_repr",
        ),
    ]
