# Generated by Django 4.1.5 on 2023-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storymap",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
