# Generated by Django 4.2 on 2023-05-02 15:42

import apps.core.models.commons
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story_map", "0004_remove_storymap_story_map_storymap_unique_active_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storymap",
            name="title",
            field=models.CharField(
                max_length=128, validators=[apps.core.models.commons.validate_name]
            ),
        ),
    ]
