# Generated by Django 4.2.3 on 2023-07-31 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
        ("story_map", "0004_remove_storymap_story_map_storymap_unique_active_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storymap",
            name="membership_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_map",
                to="collaboration.membershiplist",
            ),
        ),
    ]
