# Generated by Django 5.2.7 on 2025-11-15 08:52
#
# Drift migration: Captures validator addition that was never migrated.
#
# IMPORTANT: This migration is IRREVERSIBLE.
# The forward migration is idempotent and safe - it updates Django's migration state to match
# the actual production database state.
#
# Rolling back this migration would remove the validate_name validator from the title field,
# which could allow invalid data to be created.
#
# STATE CHANGES CAPTURED (commented out to show what Django detected):
#
# migrations.AlterField(
#     model_name='storymap',
#     name='title',
#     field=models.CharField(
#         max_length=128,
#         validators=[apps.core.models.commons.validate_name]
#     ),
# ),

import apps.core.models.commons
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_map', '0006_storymap_published_configuration_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='storymap',
                    name='title',
                    field=models.CharField(max_length=128, validators=[apps.core.models.commons.validate_name]),
                ),
            ],
            database_operations=[
                # Validators don't affect database schema, so no database changes needed
                migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
            ],
        ),
    ]
