# Generated by Django 3.2.9 on 2021-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
