# Copyright © 2021-2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 3.2.9 on 2021-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_group_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupassociation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="landscapegroup",
            options={},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={},
        ),
        migrations.AddConstraint(
            model_name="groupassociation",
            constraint=models.UniqueConstraint(
                fields=("parent_group", "child_group"), name="unique_group_association"
            ),
        ),
        migrations.AddConstraint(
            model_name="landscapegroup",
            constraint=models.UniqueConstraint(
                fields=("group", "landscape"), name="unique_landscape_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(fields=("group", "user"), name="unique_membership"),
        ),
    ]
