# Generated by Django 3.2.9 on 2021-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_group_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupassociation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="landscapegroup",
            options={},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={},
        ),
        migrations.AddConstraint(
            model_name="groupassociation",
            constraint=models.UniqueConstraint(
                fields=("parent_group", "child_group"), name="unique_group_association"
            ),
        ),
        migrations.AddConstraint(
            model_name="landscapegroup",
            constraint=models.UniqueConstraint(
                fields=("group", "landscape"), name="unique_landscape_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(fields=("group", "user"), name="unique_membership"),
        ),
    ]
