# Generated by Django 3.2.11 on 2022-01-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20211209_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(null=True),
        ),
    ]
