# Generated by Django 3.2.11 on 2022-01-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20220113_1747"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={},
        ),
    ]
