# Generated by Django 3.2.11 on 2022-01-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20220118_2227"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupassociation",
            name="unique_group_association",
        ),
        migrations.RemoveConstraint(
            model_name="landscapegroup",
            name="unique_landscape_group",
        ),
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_membership",
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name="landscape",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="groupassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("parent_group", "child_group"),
                name="unique_group_association",
            ),
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slug",),
                name="unique_active_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="landscapegroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("group", "landscape"),
                name="unique_active_landscape_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("group", "user"),
                name="unique_active_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("email",),
                name="unique_active_email",
            ),
        ),
    ]
