# Generated by Django 4.0.1 on 2022-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="area_polygon",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
