# Generated by Django 4.0.3 on 2022-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userpreference_userpreference_unique_user_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscape',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
