# Generated by Django 4.0.4 on 2022-06-14 17:40

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_group_deleted_by_cascade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="membership_type",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="membership_status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("pending", "Pending")],
                default="approved",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=128, unique=True, validators=[apps.core.models.commons.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="landscape",
            name="name",
            field=models.CharField(
                max_length=128, unique=True, validators=[apps.core.models.commons.validate_name]
            ),
        ),
    ]
