# Generated by Django 4.1 on 2022-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_landscape_profile_and_taxonomies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxonomyterm",
            name="type",
            field=models.CharField(
                choices=[
                    ("ecosystem-type", "Ecosystem Type"),
                    ("language", "Language"),
                    ("livelihood", "Livelihood"),
                    ("commodity", "Commodity"),
                    ("organization", "Organization"),
                ],
                max_length=128,
                unique=True,
            ),
        ),
    ]
