# Copyright © 2021-2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.1 on 2022-10-14 21:00

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_taxonomyterm_type_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxonomyterm",
            name="name",
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="value_en",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="value_es",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="value_original",
            field=models.CharField(
                default="", max_length=128, validators=[apps.core.models.commons.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="taxonomyterm",
            name="type",
            field=models.CharField(
                choices=[
                    ("ecosystem-type", "Ecosystem Type"),
                    ("language", "Language"),
                    ("livelihood", "Livelihood"),
                    ("commodity", "Commodity"),
                    ("organization", "Organization"),
                ],
                max_length=128,
            ),
        ),
    ]
