# Generated by Django 4.1 on 2022-10-14 21:00

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_taxonomyterm_type_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxonomyterm",
            name="name",
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="value_en",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="value_es",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="value_original",
            field=models.CharField(
                default="", max_length=128, validators=[apps.core.models.commons.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="taxonomyterm",
            name="type",
            field=models.CharField(
                choices=[
                    ("ecosystem-type", "Ecosystem Type"),
                    ("language", "Language"),
                    ("livelihood", "Livelihood"),
                    ("commodity", "Commodity"),
                    ("organization", "Organization"),
                ],
                max_length=128,
            ),
        ),
    ]
