# Generated by Django 4.1 on 2022-10-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_taxonomyterm_name_taxonomyterm_value_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landscape",
            name="area_type",
        ),
        migrations.AddField(
            model_name="landscape",
            name="area_types",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
