# Generated by Django 4.1 on 2022-10-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_landscape_population_development_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscapegroup",
            name="partnership_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
