# Generated by Django 4.1 on 2022-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_landscapegroup_partnership_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="partnership_status",
            field=models.CharField(
                choices=[("no", "No"), ("in-progress", "In Progress"), ("yes", "Yes")],
                default="no",
                max_length=32,
            ),
        ),
    ]
