# Copyright © 2021-2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.1 on 2022-11-07 15:24

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_initial_taxonomy_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="profile_image",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="landscape",
            name="profile_image_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
