# Generated by Django 4.1 on 2022-11-07 15:24

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_initial_taxonomy_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="profile_image",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="landscape",
            name="profile_image_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
