# Generated by Django 4.1 on 2022-11-03 18:18

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_initial_taxonomy_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="groupassociation",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="landscape",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="landscapegroup",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="taxonomyterm",
            name="value_original",
            field=models.CharField(
                max_length=128, validators=[apps.core.models.commons.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
