# Copyright © 2021-2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.1 on 2022-11-03 18:20

from django.db import connection, migrations

from apps.core.models import BackgroundTask


def forwards_func(apps, schema_editor):
    existing_tables = connection.introspection.table_names()
    table_name = BackgroundTask._meta.db_table
    if table_name not in existing_tables:
        schema_editor.create_model(BackgroundTask)


def backwards_func(app, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_calculate_polygon_areas"),
    ]

    operations = [migrations.RunPython(forwards_func, backwards_func)]
