# Generated by Django 4.1.3 on 2022-12-13 20:26

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_spanish_taxonomy_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landscape",
            name="name",
            field=models.CharField(
                max_length=128, validators=[apps.core.models.commons.validate_name]
            ),
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="core_landscape_name_key",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=128, validators=[apps.core.models.commons.validate_name]
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="core_group_name_key",
            ),
        ),
    ]
