# Generated by Django 4.1.3 on 2023-01-04 20:33

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_group_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landscape",
            name="partnership_status",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("no", "No"), ("in-progress", "In Progress"), ("yes", "Yes")],
                default="",
                max_length=32,
            ),
        ),
    ]
