# Generated by Django 4.1.3 on 2023-01-06 18:00

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_taxonomy_terms_agricultural_production"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landscapedevelopmentstrategy",
            name="other_information",
        ),
    ]
