# Generated by Django 4.1.3 on 2023-01-06 18:03

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_landscapedevelopmentstrategy_other_information"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    """
                    DELETE FROM core_landscape_taxonomy_terms
                    WHERE taxonomyterm_id IN (
                        SELECT id
                        FROM core_taxonomyterm
                        WHERE type = 'livelihood' AND value_original = 'Other'
                    );
                    """
                )
            ],
        ),
        migrations.RunSQL(
            sql=[
                (
                    """
                    DELETE FROM core_taxonomyterm
                    WHERE type = 'livelihood' AND value_original = 'Other';
                    """
                )
            ],
        ),
    ]
