# Generated by Django 4.1.3 on 2023-01-06 20:11

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_taxonomy_terms_remove_other"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="landscapegroup",
            name="unique_active_landscape_group",
        ),
        migrations.AddConstraint(
            model_name="landscapegroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("group", "landscape", "is_partnership"),
                name="unique_active_landscape_group",
            ),
        ),
    ]
