# Generated by Django 4.1.3 on 2023-01-06 21:12

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_landscapegroup_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscapedevelopmentstrategy",
            name="opportunities",
            field=models.TextField(blank=True, default=""),
        ),
    ]
