# Copyright © 2021-2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.1.3 on 2023-01-09 18:54

from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_landscapedevelopmentstrategy_opportunities"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="group",
            name="core_group_unique_active_slug",
        ),
        migrations.RemoveConstraint(
            model_name="group",
            name="core_group_name_key",
        ),
        migrations.RemoveConstraint(
            model_name="landscape",
            name="core_landscape_unique_active_slug",
        ),
        migrations.RemoveConstraint(
            model_name="landscape",
            name="core_landscape_name_key",
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slug",),
                name="core_group_unique_active_slug",
                violation_error_message="slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="core_group_unique_active_name",
                violation_error_message="name",
            ),
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slug",),
                name="core_landscape_unique_active_slug",
                violation_error_message="slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="core_landscape_unique_active_name",
                violation_error_message="name",
            ),
        ),
    ]
