# Generated by Django 4.1.5 on 2023-01-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_group_core_group_unique_active_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, default="", max_length=2048),
        ),
    ]
