# Generated by Django 4.2 on 2023-04-04 15:23

from django.db import migrations
from django.db.models import Q


def update_rows(apps, schema_editor):
    User = apps.get_model("core", "User")
    UserPreference = apps.get_model("core", "UserPreference")

    for obj in User.objects.filter(~Q(preferences__key="notifications")):
        UserPreference.objects.create(user=obj, key="notifications", value="true")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_group_description"),
    ]

    operations = [migrations.RunPython(update_rows)]
