# Generated by Django 4.2 on 2023-04-11 21:51

from django.db import migrations, models

from apps.core.gis.utils import calculate_geojson_centroid


def calculate_center_coordinates(apps, schema_editor):
    Landscape = apps.get_model("core", "Landscape")
    missing_center_coordinates = Landscape.objects.filter(
        area_polygon__isnull=False, center_coordinates__isnull=True
    )
    for landscape in missing_center_coordinates:
        landscape.center_coordinates = calculate_geojson_centroid(landscape.area_polygon)
    Landscape.objects.bulk_update(missing_center_coordinates, ["center_coordinates"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="center_coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(calculate_center_coordinates),
    ]
