# Generated by Django 4.2 on 2023-04-28 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models.commons


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_website_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_test_user",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
