# Generated by Django 4.2 on 2023-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_landscapedefaultgroup_alter_group_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="enroll_method",
            field=models.CharField(
                choices=[("join", "Join"), ("invite", "Invite"), ("both", "Both")],
                default="join",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="membership_type",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=32
            ),
        ),
    ]
