# Generated by Django 4.2.1 on 2023-05-18 16:24

import apps.core.models.commons
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_landscapedefaultgroup_group_enroll_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landscape",
            name="taxonomy_terms",
            field=models.ManyToManyField(blank=True, to="core.taxonomyterm"),
        ),
    ]
