# Copyright © 2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.2.4 on 2023-09-08 15:33

from django.db import migrations
from django.db.models import Q


def update_rows(apps, schema_editor):
    UserPreference = apps.get_model("core", "UserPreference")
    UserPreference.objects.filter(key="notifications").update(key="group_notifications")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_landscapedefaultgroup_alter_group_deleted_at_and_more"),
    ]

    operations = [migrations.RunPython(update_rows)]
