# Copyright © 2024 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 5.0 on 2024-01-08 15:59

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_group_membership_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedresource",
            name="share_access",
            field=models.CharField(
                choices=[
                    ("no", "No share access"),
                    ("all", "Anyone with the link"),
                    ("target_members", "Only tagert members"),
                ],
                default="no",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="share_uuid",
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="sharedresource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("share_uuid",),
                name="unique_share_uuid",
            ),
        ),
    ]
