# Generated by Django 5.2.7 on 2025-11-15 08:52
#
# This migration captures model drift from django-safedelete 1.3.0 upgrade (Sept 2022) and other
# model changes that were applied to production but never recorded in migrations. Developers
# removed these auto-generated operations from migrations 0041-0043, causing drift.
#
# IMPORTANT: This migration is IRREVERSIBLE.
# The forward migration is idempotent and safe - it updates Django's migration state to match
# the actual production database state that has existed since 2022.
#
# Rolling back this migration would:
# - Drop db_index from deleted_at fields (performance regression)
# - Revert field choices to outdated values (potential data issues)
# - Remove models that production code depends on (breaking changes)
#
# Therefore, reverse migration is disabled to prevent accidental production breakage.
#
# STATE CHANGES CAPTURED (commented out to show what Django detected):
#
# migrations.CreateModel(
#     name='LandscapeDefaultGroup',
#     fields=[],
#     options={'proxy': True, 'indexes': [], 'constraints': []},
#     bases=('core.group',),
# ),
#
# migrations.AlterModelOptions(
#     name='landscapedevelopmentstrategy',
#     options={'verbose_name_plural': 'Landscape development strategies'},
# ),
#
# migrations.AlterModelOptions(
#     name='sharedresource',
#     options={},
# ),
#
# migrations.AlterField(
#     model_name='group',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),
#
# migrations.AlterField(
#     model_name='group',
#     name='group_associations',
#     field=models.ManyToManyField(through='core.GroupAssociation', through_fields=('parent_group', 'child_group'), to='core.group'),
# ),
#
# migrations.AlterField(
#     model_name='groupassociation',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),
#
# migrations.AlterField(
#     model_name='landscape',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),
#
# migrations.AlterField(
#     model_name='landscape',
#     name='partnership_status',
#     field=models.CharField(
#         blank=True,
#         choices=[('', 'None'), ('no', 'No'), ('in-progress', 'In Progress'), ('yes', 'Yes')],
#         default='',
#         max_length=32
#     ),
# ),
#
# migrations.AlterField(
#     model_name='landscapegroup',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),
#
# migrations.AlterField(
#     model_name='membership',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),
#
# migrations.AlterField(
#     model_name='membership',
#     name='user_role',
#     field=models.CharField(
#         choices=[('manager', 'Manager'), ('member', 'Member')],
#         default='member',
#         max_length=64
#     ),
# ),
#
# migrations.AlterField(
#     model_name='sharedresource',
#     name='share_access',
#     field=models.CharField(
#         choices=[('all', 'Anyone with the link'), ('members', 'Only members')],
#         default='members',
#         max_length=32
#     ),
# ),
#
# migrations.AlterField(
#     model_name='sharedresource',
#     name='share_uuid',
#     field=models.UUIDField(default=uuid.uuid4),
# ),
#
# migrations.AlterField(
#     model_name='taxonomyterm',
#     name='type',
#     field=models.CharField(
#         choices=[
#             ('ECOSYSTEM_TYPE', 'Ecosystem Type'),
#             ('LANGUAGE', 'Language'),
#             ('LIVELIHOOD', 'Livelihood'),
#             ('COMMODITY', 'Commodity'),
#             ('ORGANIZATION', 'Organization'),
#             ('AGRICULTURAL_PRODUCTION_METHOD', 'Agricultural Production Method')
#         ],
#         max_length=128
#     ),
# ),
#
# migrations.AlterField(
#     model_name='taxonomyterm',
#     name='value_original',
#     field=models.CharField(max_length=128, validators=[apps.core.models.commons.validate_name]),
# ),
#
# migrations.AlterField(
#     model_name='user',
#     name='deleted_at',
#     field=models.DateTimeField(db_index=True, editable=False, null=True),
# ),
#
# migrations.RunPython(
#     create_background_task_if_needed,
#     reverse_background_task,
# ),

import apps.core.models.commons
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models


def create_background_task_if_needed(apps, schema_editor):
    """
    Conditionally create BackgroundTask table if it doesn't exist.
    This handles the case where the table was already created by migration 0027.
    """
    from apps.core.models import BackgroundTask

    existing_tables = connection.introspection.table_names()
    table_name = BackgroundTask._meta.db_table
    if table_name not in existing_tables:
        schema_editor.create_model(BackgroundTask)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_sharedresource_renamed_target_members'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Update Django's migration state to match production reality
                migrations.CreateModel(
                    name='LandscapeDefaultGroup',
                    fields=[
                    ],
                    options={
                        'proxy': True,
                        'indexes': [],
                        'constraints': [],
                    },
                    bases=('core.group',),
                ),
                migrations.AlterModelOptions(
                    name='landscapedevelopmentstrategy',
                    options={'verbose_name_plural': 'Landscape development strategies'},
                ),
                migrations.AlterModelOptions(
                    name='sharedresource',
                    options={},
                ),
                migrations.AlterField(
                    model_name='group',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                migrations.AlterField(
                    model_name='group',
                    name='group_associations',
                    field=models.ManyToManyField(through='core.GroupAssociation', through_fields=('parent_group', 'child_group'), to='core.group'),
                ),
                migrations.AlterField(
                    model_name='groupassociation',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                migrations.AlterField(
                    model_name='landscape',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                migrations.AlterField(
                    model_name='landscape',
                    name='partnership_status',
                    field=models.CharField(blank=True, choices=[('', 'None'), ('no', 'No'), ('in-progress', 'In Progress'), ('yes', 'Yes')], default='', max_length=32),
                ),
                migrations.AlterField(
                    model_name='landscapegroup',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                migrations.AlterField(
                    model_name='membership',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                migrations.AlterField(
                    model_name='membership',
                    name='user_role',
                    field=models.CharField(choices=[('manager', 'Manager'), ('member', 'Member')], default='member', max_length=64),
                ),
                migrations.AlterField(
                    model_name='sharedresource',
                    name='share_access',
                    field=models.CharField(choices=[('all', 'Anyone with the link'), ('members', 'Only members')], default='members', max_length=32),
                ),
                migrations.AlterField(
                    model_name='sharedresource',
                    name='share_uuid',
                    field=models.UUIDField(default=uuid.uuid4),
                ),
                migrations.AlterField(
                    model_name='taxonomyterm',
                    name='type',
                    field=models.CharField(choices=[('ECOSYSTEM_TYPE', 'Ecosystem Type'), ('LANGUAGE', 'Language'), ('LIVELIHOOD', 'Livelihood'), ('COMMODITY', 'Commodity'), ('ORGANIZATION', 'Organization'), ('AGRICULTURAL_PRODUCTION_METHOD', 'Agricultural Production Method')], max_length=128),
                ),
                migrations.AlterField(
                    model_name='taxonomyterm',
                    name='value_original',
                    field=models.CharField(max_length=128, validators=[apps.core.models.commons.validate_name]),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='deleted_at',
                    field=models.DateTimeField(db_index=True, editable=False, null=True),
                ),
            ],
            database_operations=[
                # Database is already in this state from production, so do nothing
                migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
            ],
        ),
        # Special handling for BackgroundTask - conditional creation with no reverse
        migrations.RunPython(
            create_background_task_if_needed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
