# Generated by Django 5.2.7 on 2025-12-02 23:15
#
# Drift migration: Captures BackgroundTask model that was added in December 2022
# but never had a migration created.
#
# IMPORTANT: This migration is IRREVERSIBLE.
# The forward migration is idempotent and safe - it updates Django's migration state to match
# the actual production database state that has existed since December 2022.
#
# Rolling back this migration would remove the BackgroundTask model from Django's migration
# state, which could cause schema detection issues.
#
# STATE CHANGES CAPTURED (commented out to show what Django detected):
#
# migrations.CreateModel(
#     name='BackgroundTask',
#     fields=[
#         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#         ('status', models.CharField(choices=[('finished', 'Finished'), ('failed', 'Failed'), ('running', 'Running')], max_length=10)),
#         ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#     ],
# ),

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_landscapedefaultgroup_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BackgroundTask',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('finished', 'Finished'), ('failed', 'Failed'), ('running', 'Running')], max_length=10)),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
            database_operations=[
                # Database table already exists in production since December 2022, so do nothing
                migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
            ],
        ),
    ]
