# Generated by Django 5.2.7 on 2025-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_landscapedefaultgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='export_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
