# Generated by Django 5.2.7 on 2025-11-15 00:51

from django.db import migrations


def create_system_export_user(apps, schema_editor):
    """
    Create the system export user used by export endpoints.
    This user bypasses user-based security filtering to allow exports.
    """
    User = apps.get_model('core', 'User')
    User.objects.get_or_create(
        email='system-export@terraso.org',
        defaults={
            'first_name': 'System',
            'last_name': 'Export'
        }
    )


def reverse_system_export_user(apps, schema_editor):
    """
    Remove the system export user.
    We use raw SQL to avoid SafeDelete complications in migrations.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "DELETE FROM core_user WHERE email = 'system-export@terraso.org'"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_export_token_to_user'),
    ]

    operations = [
        migrations.RunPython(
            create_system_export_user,
            reverse_system_export_user,
        ),
    ]
