# Generated by Django 5.2.7 on 2026-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0053_backgroundtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('apple_sub__isnull', False), ('deleted_at__isnull', True)), fields=('apple_sub',), name='unique_active_apple_sub'),
        ),
    ]
