# Generated by Django 4.2.4 on 2023-08-23 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0014_site_privacy_alter_project_description"),
        ("soil_id", "0002_depthdependentsoildata_bedrock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depthdependentsoildata",
            name="bedrock",
        ),
        migrations.RemoveField(
            model_name="soildata",
            name="slope_shape",
        ),
        migrations.AddField(
            model_name="soildata",
            name="bedrock",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_aspect",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(359),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_landscape_position",
            field=models.CharField(
                choices=[
                    ("Hills/Mountains", "Hills/Mountains"),
                    ("Summit", "Summit"),
                    ("Shoulder", "Shoulder"),
                    ("Backslope", "Backslope"),
                    ("Alluvial Fan", "Alluvial Fan"),
                    ("Floodpain/Basin", "Floodpain/Basin"),
                    ("Terrace", "Terrace"),
                    ("Tread", "Tread"),
                    ("Riser", "Riser"),
                    ("Flat/Low Rolling Plain", "Flat/Low Rolling Plain"),
                    ("Playa", "Playa"),
                    ("Dunes", "Dunes"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_steepness_degree",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_steepness_percent",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_steepness_select",
            field=models.CharField(
                choices=[
                    ("0 - 2% (flat)", "0 - 2% (flat)"),
                    ("2 - 5% (gentle)", "2 - 5% (gentle)"),
                    ("5 - 10% (moderate)", "5 - 10% (moderate)"),
                    ("10 - 15% (rolling)", "10 - 15% (rolling)"),
                    ("15 - 30% (hilly)", "15 - 30% (hilly)"),
                    ("30 - 50% (steep)", "30 - 50% (steep)"),
                    ("50 - 60% (moderately steep)", "50 - 60% (moderately steep)"),
                    ("60 - 100% (very steep)", "60 - 100% (very steep)"),
                    ("100%+ (steepest)", "100%+ (steepest)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="sodium_absorption_ratio",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=100,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="structure",
            field=models.CharField(
                choices=[
                    ("granular", "Granular"),
                    ("subangular blocky", "Subangular Blocky"),
                    ("angular blocky", "Angular Blocky"),
                    ("lenticular", "Lenticular"),
                    ("play", "Play"),
                    ("wedge", "Wedge"),
                    ("prismatic", "Prismatic"),
                    ("columnar", "Columnar"),
                    ("single grain", "Single Grain"),
                    ("massive", "Massive"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="soildata",
            name="cross_slope",
            field=models.CharField(
                choices=[("concave", "Concave"), ("convex", "Convex"), ("linear", "Linear")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="soildata",
            name="down_slope",
            field=models.CharField(
                choices=[("concave", "Concave"), ("convex", "Convex"), ("linear", "Linear")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="soildata",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soil_data",
                to="project_management.site",
            ),
        ),
    ]
