# Copyright © 2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.2.5 on 2023-09-07 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0014_site_privacy_alter_project_description"),
        ("soil_id", "0002_depthdependentsoildata_bedrock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depthdependentsoildata",
            options={},
        ),
        migrations.RemoveField(
            model_name="depthdependentsoildata",
            name="bedrock",
        ),
        migrations.RemoveField(
            model_name="depthdependentsoildata",
            name="carbonate",
        ),
        migrations.RemoveField(
            model_name="depthdependentsoildata",
            name="color_hue_substeps",
        ),
        migrations.RenameField(
            model_name="depthdependentsoildata", old_name="depth_bottom", new_name="depth_end"
        ),
        migrations.RenameField(
            model_name="depthdependentsoildata", old_name="depth_top", new_name="depth_start"
        ),
        migrations.RenameField(
            model_name="depthdependentsoildata", old_name="soil_data_input", new_name="soil_data"
        ),
        migrations.RemoveField(
            model_name="soildata",
            name="slope_shape",
        ),
        migrations.AddField(
            model_name="depthdependentsoildata",
            name="carbonates",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONEFFERVESCENT", "noneffervescent — No bubbles form"),
                    ("VERY_SLIGHTLY_EFFERVESCENT", "very slightly effervescent — Few bubbles form"),
                    ("SLIGHTLY_EFFERVESCENT", "slightly effervescent — Numerous bubbles form"),
                    ("STRONGLY_EFFERVESCENT", "strongly effervescent — Bubbles form a low foam"),
                    (
                        "VIOLENTLY_EFFERVESCENT",
                        "violently effervescent — Bubbles rapidly form a thick foam",
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="depthdependentsoildata",
            name="color_hue_substep",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBSTEP_2_5", "2.5"),
                    ("SUBSTEP_5", "5"),
                    ("SUBSTEP_7_5", "7.5"),
                    ("SUBSTEP_10", "10"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="bedrock",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_aspect",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(359),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_landscape_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HILLS_MOUNTAINS", "Hills/Mountains"),
                    ("HILLS_MOUNTAINS_SUMMIT", "Hills/Mountains (Summit)"),
                    ("HILLS_MOUNTAINS_SHOULDER", "Hills/Mountains (Shoulder)"),
                    ("HILLS_MOUNTAINS_BACKSLOPE", "Hills/Mountains (Backslope)"),
                    ("ALLUVIAL_FAN", "Alluvial Fan"),
                    ("FLOODPLAIN_BASIN", "Floodplain/Basin"),
                    ("TERRACE", "Terrace"),
                    ("TERRACE_TREAD", "Terrace (Tread)"),
                    ("TERRACE_RISER", "Terrace (Riser)"),
                    ("FLAT_LOW_ROLLING_PLAIN", "Flat/Low Rolling Plain"),
                    ("PLAYA", "Playa"),
                    ("DUNES", "Dunes"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_steepness_degree",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_steepness_percent",
            field=models.IntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="soildata",
            name="slope_steepness_select",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLAT", "0 - 2% (flat)"),
                    ("GENTLE", "2 - 5% (gentle)"),
                    ("MODERATE", "5 - 10% (moderate)"),
                    ("ROLLING", "10 - 15% (rolling)"),
                    ("HILLY", "15 - 30% (hilly)"),
                    ("STEEP", "30 - 50% (steep)"),
                    ("MODERATELY_STEEP", "50 - 60% (moderately steep)"),
                    ("VERY_STEEP", "60 - 100% (very steep)"),
                    ("STEEPEST", "100%+ (steepest)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="color_chroma",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHROMA_1", "1"),
                    ("CHROMA_2", "2"),
                    ("CHROMA_3", "3"),
                    ("CHROMA_4", "4"),
                    ("CHROMA_5", "5"),
                    ("CHROMA_6", "6"),
                    ("CHROMA_7", "7"),
                    ("CHROMA_8", "8"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="color_hue",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "R"),
                    ("YR", "YR"),
                    ("Y", "Y"),
                    ("GY", "GY"),
                    ("G", "G"),
                    ("B", "B"),
                    ("BG", "BG"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="color_value",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VALUE_2_5", "2.5"),
                    ("VALUE_3", "3"),
                    ("VALUE_4", "4"),
                    ("VALUE_5", "5"),
                    ("VALUE_6", "6"),
                    ("VALUE_7", "7"),
                    ("VALUE_8", "8"),
                    ("VALUE_8_5", "8.5"),
                    ("VALUE_9", "9"),
                    ("VALUE_9_5", "9.5"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="conductivity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="conductivity_test",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SATURATED_PASTE", "Saturated Paste"),
                    ("SOIL_WATER_1_1", "1:1 soil/water"),
                    ("SOIL_WATER_1_2", "1:2 soil/water"),
                    ("SOIL_CONTACT_PROBE", "Soil Contact Probe"),
                    ("OTHER", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="conductivity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MILLISIEMENS_CENTIMETER", "mS/cm"),
                    ("MILLIMHOS_CENTIMETER", "mmhos/cm"),
                    ("MICROSIEMENS_METER", "µS/m"),
                    ("MILLISIEMENS_METER", "mS/m"),
                    ("DECISIEMENS_METER", "dS/m"),
                    ("OTHER", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="ph",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(14.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="ph_testing_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INDICATOR_STRIP", "pH indicator strip"),
                    ("INDICATOR_SOLUTION", "pH indicator solution"),
                    ("METER", "pH meter"),
                    ("OTHER", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="ph_testing_solution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOIL_WATER_1_1", "1:1 soil/water"),
                    ("SOIL_WATER_1_2", "1:2 soil/water"),
                    ("SOIL_WATER_1_2_5", "1:2.5 soil/water"),
                    ("SOIL_WATER_1_5", "1:5 soil/water"),
                    ("SOIL_CACL2_1_1", "1:1 soil/0.1 M CaCL2"),
                    ("SOIL_CACL2_1_2", "1:2 soil/0.1 M CaCL2"),
                    ("SOIL_CACL2_1_5", "1:5 soil/0.1 M CaCL2"),
                    ("SOIL_KCL_1_1", "1:1 soil/1.0 M KCL"),
                    ("SOIL_KCL_1_2_5", "1:2.5 soil/1.0 M KCL"),
                    ("SOIL_KCL_1_5", "1:5 soil/1.0 M KCL"),
                    ("SATURATED_PASTE_EXTRACT", "Saturated Paste Extract"),
                    ("OTHER", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="rock_fragment_volume",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VOLUME_0_1", "0 — 1%"),
                    ("VOLUME_1_15", "1 — 15%"),
                    ("VOLUME_15_35", "15 — 35%"),
                    ("VOLUME_35_60", "35 — 60%"),
                    ("VOLUME_60", "> 60%"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="sodium_absorption_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=100,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="soil_organic_carbon",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="soil_organic_carbon_testing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRY_COMBUSTION", "Dry Combustion"),
                    ("WET_OXIDATION", "Wet oxidation (Walkey—Black)"),
                    ("LOSS_ON_IGNITION", "Loss—on—ignition"),
                    ("REFLECTANCE_SPECTROSCOPY", "Reflectance Spectroscopy"),
                    ("FIELD_REFLECTOMETER", "Field Reflectometer"),
                    ("OTHER", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="soil_organic_matter",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="soil_organic_matter_testing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRY_COMBUSTION", "Dry Combustion"),
                    ("WET_OXIDATION", "Wet oxidation (Walkey—Black)"),
                    ("LOSS_ON_IGNITION", "Loss—on—ignition"),
                    ("REFLECTANCE_SPECTROSCOPY", "Reflectance Spectroscopy"),
                    ("FIELD_REFLECTOMETER", "Field Reflectometer"),
                    ("OTHER", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GRANULAR", "Granular"),
                    ("SUBANGULAR_BLOCKY", "Subangular Blocky"),
                    ("ANGULAR_BLOCKY", "Angular Blocky"),
                    ("LENTICULAR", "Lenticular"),
                    ("PLAY", "Play"),
                    ("WEDGE", "Wedge"),
                    ("PRISMATIC", "Prismatic"),
                    ("COLUMNAR", "Columnar"),
                    ("SINGLE_GRAIN", "Single Grain"),
                    ("MASSIVE", "Massive"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="texture",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SAND", "Sand"),
                    ("LOAMY_SAND", "Loamy Sand"),
                    ("SANDY_LOAM", "Sandy Loam"),
                    ("SILT_LOAM", "Silt Loam"),
                    ("SILT", "Silt"),
                    ("LOAM", "Loam"),
                    ("SANDY_CLAY_LOAM", "Sandy Clay Loam"),
                    ("SILTY_CLAY_LOAM", "Silty Clay Loam"),
                    ("CLAY_LOAM", "Clay Loam"),
                    ("SANDY_CLAY", "Sandy Clay"),
                    ("SILTY_CLAY", "Silty Clay"),
                    ("CLAY", "Clay"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="depth_end",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(200)]
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="depth_start",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(200)]
            ),
        ),
        migrations.AlterField(
            model_name="depthdependentsoildata",
            name="soil_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depth_dependent_data",
                to="soil_id.soildata",
            ),
        ),
        migrations.AlterField(
            model_name="soildata",
            name="cross_slope",
            field=models.CharField(
                blank=True,
                choices=[("CONCAVE", "Concave"), ("CONVEX", "Convex"), ("LINEAR", "Linear")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="soildata",
            name="down_slope",
            field=models.CharField(
                blank=True,
                choices=[("CONCAVE", "Concave"), ("CONVEX", "Convex"), ("LINEAR", "Linear")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="soildata",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soil_data",
                to="project_management.site",
            ),
        ),
        migrations.AddConstraint(
            model_name="depthdependentsoildata",
            constraint=models.UniqueConstraint(
                fields=("soil_data", "depth_start", "depth_end"), name="unique_depth_interval"
            ),
        ),
        migrations.AddConstraint(
            model_name="depthdependentsoildata",
            constraint=models.CheckConstraint(
                condition=models.Q(("depth_start__lt", models.F("depth_end"))),
                name="depth_interval_coherence",
            ),
        ),
    ]
