# Generated by Django 4.2.5 on 2023-09-21 15:54

from django.db import migrations, models

import apps.soil_id.models.soil_data


class Migration(migrations.Migration):
    dependencies = [
        ("soil_id", "0003_alter_depthdependentsoildata_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soildata",
            name="depth_intervals",
            field=models.JSONField(
                blank=True,
                default=apps.soil_id.models.soil_data.default_depth_intervals,
                validators=[apps.soil_id.models.soil_data.validate_depth_intervals],
            ),
        ),
    ]
