# Copyright © 2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.2.6 on 2023-10-16 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("soil_id", "0006_soildata_flooding_select_soildata_grazing_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soildata",
            old_name="grazing",
            new_name="grazing_select",
        ),
    ]
