# Generated by Django 4.2.6 on 2023-10-16 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("soil_id", "0006_soildata_flooding_select_soildata_grazing_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soildata",
            old_name="grazing",
            new_name="grazing_select",
        ),
    ]
