# Generated by Django 4.2.7 on 2023-12-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soil_id", "0007_rename_grazing_soildata_grazing_select"),
    ]

    operations = [
        migrations.AddField(
            model_name="soildata",
            name="depth_interval_preset",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LANDPKS", "Landpks"),
                    ("NRCS", "Nrcs"),
                    ("NONE", "None"),
                    ("CUSTOM", "Custom"),
                ],
                null=True,
            ),
        ),
    ]
