# Generated by Django 5.0.1 on 2024-01-18 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soil_id", "0008_soildata_depth_interval_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="depthdependentsoildata",
            name="clay_percent",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="soildata",
            name="depth_interval_preset",
            field=models.CharField(
                blank=True,
                choices=[("LANDPKS", "Landpks"), ("NRCS", "Nrcs"), ("CUSTOM", "Custom")],
                null=True,
            ),
        ),
    ]
