# Generated by Django 5.0.1 on 2024-02-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_id", "0009_depthdependentsoildata_clay_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depthdependentsoildata",
            name="color_photo_lighting_condition",
            field=models.CharField(
                blank=True, choices=[("EVEN", "Even"), ("UNEVEN", "Uneven")], null=True
            ),
        ),
        migrations.AddField(
            model_name="depthdependentsoildata",
            name="color_photo_soil_condition",
            field=models.CharField(
                blank=True, choices=[("MOIST", "Moist"), ("DRY", "Dry")], null=True
            ),
        ),
    ]
