# Copyright © 2024 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 5.0.6 on 2024-06-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_id", "0013_remove_projectsoilsettings_measurement_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilIdCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("failure_reason", models.TextField(null=True)),
                ("soil_list_json", models.JSONField(null=True)),
                ("rank_data_csv", models.TextField(null=True)),
                ("map_unit_component_data_csv", models.TextField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="soilidcache",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="coordinate_index"
            ),
        ),
    ]
