# Generated by Django 5.0.6 on 2024-06-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_id", "0013_remove_projectsoilsettings_measurement_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilIdCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("failure_reason", models.TextField(null=True)),
                ("soil_list_json", models.JSONField(null=True)),
                ("rank_data_csv", models.TextField(null=True)),
                ("map_unit_component_data_csv", models.TextField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="soilidcache",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="coordinate_index"
            ),
        ),
    ]
