# Generated by Django 5.0.6 on 2024-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_id", "0014_soilidcache_soilidcache_coordinate_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="soildata",
            name="selected_soil_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
