# Copyright © 2024 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 5.1 on 2024-08-28 22:47

import uuid

import django.utils.timezone
from django.db import migrations, models


def delete_cache(apps, schema_editor):
    SoilIdCache = apps.get_model("soil_id", "SoilIdCache")

    SoilIdCache.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("soil_id", "0016_alter_soildata_slope_steepness_degree_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_cache),
        migrations.AddField(
            model_name="soilidcache",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="soilidcache",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="soilidcache",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="soilidcache",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="soilidcache",
            name="id",
        ),
        migrations.AddField(
            model_name="soilidcache",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
