# Copyright © 2024 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 5.1.1 on 2024-10-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soil_id", "0017_alter_soilidcache"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectsoilsettings",
            options={
                "get_latest_by": "-created_at",
                "ordering": ["created_at"],
                "verbose_name_plural": "project soil settings",
            },
        ),
        migrations.AlterModelOptions(
            name="soildata",
            options={
                "get_latest_by": "-created_at",
                "ordering": ["created_at"],
                "verbose_name_plural": "soil data",
            },
        ),
        migrations.AlterModelOptions(
            name="soilidcache",
            options={"verbose_name": "Soil ID Cache", "verbose_name_plural": "Soil ID Cache"},
        ),
    ]
