# Generated by Django 5.1.3 on 2024-11-18 20:52

import uuid

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0028_site_elevation"),
        ("soil_id", "0020_alter_projectsoilsettings_slope_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilMetadata",
            fields=[
                ("deleted_at", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_soil_id", models.CharField(blank=True, null=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_metadata",
                        to="project_management.site",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "soil metadata",
                "ordering": ["created_at"],
                "get_latest_by": "-created_at",
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
