# Generated by Django 5.2.1 on 2025-05-14 01:53

from django.db import migrations, models

def update_rows(apps, schema_editor):
    SoilIdCache = apps.get_model("soil_id", "SoilIdCache")
    SoilIdCache.objects.filter(failure_reason__isnull=True).update(data_region="US")

class Migration(migrations.Migration):

    dependencies = [
        ('soil_id', '0021_soilmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilidcache',
            name='data_region',
            field=models.CharField(choices=[('US', 'Us'), ('GLOBAL', 'Global')], null=True),
        ),
        migrations.RunPython(update_rows),
    ]
