# Generated by Django 5.2.7 on 2026-04-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_id', '0023_soilmetadata_user_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soildatahistory',
            options={'get_latest_by': '-created_at', 'ordering': ['created_at'], 'verbose_name_plural': 'History: SoilDataHistory'},
        ),
    ]
