# Generated by Django 5.2.7 on 2026-06-25 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil_id', '0024_alter_soildatahistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depthdependentsoildata',
            name='depth_interval_end',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='projectdepthinterval',
            name='depth_interval_end',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='soildatadepthinterval',
            name='depth_interval_end',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
