# Generated by Django 4.1.7 on 2023-04-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soilproj", "0002_project_projectmembership_project_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="soilproj.project",
                verbose_name="project to which the site belongs",
            ),
        ),
    ]
