# Generated by Django 4.2 on 2023-05-02 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="site",
            name="project_management_site_unique_active_name",
        ),
    ]
