# Generated by Django 4.2 on 2023-04-26 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0001_squashed_0002_project_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="site",
            name="project_management_site_unique_active_slug",
        ),
        migrations.RemoveField(
            model_name="site",
            name="slug",
        ),
        migrations.AddField(
            model_name="site",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner to which the site belongs",
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("project__isnull", False), ("owner__isnull", False), _connector="OR"),
                    models.Q(("project__isnull", True), ("owner__isnull", True), _connector="OR"),
                ),
                name="site_must_be_owned_once",
            ),
        ),
    ]
