# Copyright © 2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.2 on 2023-04-26 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0001_squashed_0002_project_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="site",
            name="project_management_site_unique_active_slug",
        ),
        migrations.RemoveField(
            model_name="site",
            name="slug",
        ),
        migrations.AddField(
            model_name="site",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner to which the site belongs",
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("project__isnull", False), ("owner__isnull", False), _connector="OR"),
                    models.Q(("project__isnull", True), ("owner__isnull", True), _connector="OR"),
                ),
                name="site_must_be_owned_once",
            ),
        ),
    ]
