# Generated by Django 4.2.1 on 2023-05-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0001_squashed_0002_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_management.project",
                verbose_name="project to which the site belongs",
            ),
        ),
    ]
