# Generated by Django 4.2.1 on 2023-05-26 19:40

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0007_remove_project_settings_site_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_management.project",
                verbose_name="project to which the site belongs",
            ),
        ),
    ]
