# Generated by Django 4.2.1 on 2023-05-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0008_alter_site_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="archived",
            field=models.BooleanField(
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="archived",
            field=models.BooleanField(
                default=False,
            ),
        ),
    ]
