# Generated by Django 4.2.3 on 2023-07-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0013_remove_site_created_by_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="privacy",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
