# Copyright © 2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 4.2.5 on 2023-09-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0005_change_collaborator_to_editor"),
        ("project_management", "0014_site_privacy_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="membership_list",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collaboration.membershiplist",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="group",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.group"
            ),
        ),
    ]
