# Generated by Django 4.2.5 on 2023-09-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0005_change_collaborator_to_editor"),
        ("project_management", "0014_site_privacy_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="membership_list",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collaboration.membershiplist",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="group",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.group"
            ),
        ),
    ]
