# Generated by Django 4.2.5 on 2023-09-14 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0018_projectmembership_projectmembershiplist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="seen_by",
            field=models.ManyToManyField(related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="site",
            name="seen_by",
            field=models.ManyToManyField(related_name="+", to=settings.AUTH_USER_MODEL),
        ),
    ]
