# Generated by Django 4.2.6 on 2023-10-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0021_sitenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="site_instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
