# Generated by Django 4.2.6 on 2023-10-26 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0021_sitenote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author to whom the note belongs",
            ),
        ),
    ]
