# Generated by Django 4.2.6 on 2023-10-30 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0021_project_site_instructions_sitenote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitenote",
            options={"get_latest_by": "-created_at", "ordering": ["created_at"]},
        ),
    ]
