# Generated by Django 4.2.6 on 2023-10-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0022_alter_sitenote_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenote",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="project_management.site",
            ),
        ),
    ]
