# Generated by Django 4.2.6 on 2023-10-30 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0022_alter_sitenote_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author of the note",
            ),
        ),
    ]
