# Copyright © 2023 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.
# Generated by Django 4.2.6 on 2023-10-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0021_project_site_instructions_sitenote.py"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="measurement_units",
            field=models.CharField(
                choices=[("METRIC", "Metric"), ("IMPERIAL", "Imperial")], default="METRIC"
            ),
        ),
    ]
