# Generated by Django 4.2.6 on 2023-11-02 15:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0024_project_measurement_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitenote",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="sitenote",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RemoveField(model_name="sitenote", name="id"),
        migrations.AddField(
            model_name="sitenote",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
