# Copyright © 2024 Technology Matters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

# Generated by Django 5.0.2 on 2024-03-14 23:15

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    Project = apps.get_model("project_management", "Project")
    Project.objects.filter(privacy_old="private").update(privacy="PRIVATE")
    Project.objects.filter(privacy_old="public").update(privacy="PUBLIC")

    Membership = apps.get_model("collaboration", "Membership")
    project_memberships = Membership.objects.filter(membership_list__project__isnull=False)
    project_memberships.filter(user_role="manager").update(user_role="MANAGER")
    project_memberships.filter(user_role="contributor").update(user_role="CONTRIBUTOR")
    project_memberships.filter(user_role="viewer").update(user_role="VIEWER")


def unmigrate_data(apps, schema_editor):
    Project = apps.get_model("project_management", "Project")
    Project.objects.filter(privacy="PRIVATE").update(privacy_old="private")
    Project.objects.filter(privacy="PUBLIC").update(privacy_old="public")

    Membership = apps.get_model("collaboration", "Membership")
    project_memberships = Membership.objects.filter(membership_list__project__isnull=False)
    project_memberships.filter(user_role="MANAGER").update(user_role="manager")
    project_memberships.filter(user_role="CONTRIBUTOR").update(user_role="contributor")
    project_memberships.filter(user_role="VIEWER").update(user_role="viewer")


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0025_sitenote_deleted_at_sitenote_deleted_by_cascade_and_more"),
        ("collaboration", "0006_membership_status_approved_lowercase"),
    ]

    operations = [
        migrations.RenameField(model_name="project", old_name="privacy", new_name="privacy_old"),
        migrations.AddField(
            model_name="project",
            name="privacy",
            field=models.CharField(
                choices=[("PRIVATE", "Private"), ("PUBLIC", "Public")],
                default="PRIVATE",
                max_length=32,
            ),
        ),
        migrations.RunPython(migrate_data, unmigrate_data),
        migrations.RemoveField(model_name="project", name="privacy_old"),
        migrations.RemoveField(
            model_name="project",
            name="measurement_units",
        ),
    ]
