# Generated by Django 5.2.7 on 2025-11-15 08:52
#
# Drift migration: Captures model Meta changes that were never migrated.
#
# IMPORTANT: This migration is IRREVERSIBLE.
# The forward migration is idempotent and safe - it updates Django's migration state to match
# the actual production database state.
#
# Rolling back this migration would revert Meta options to outdated values, which could
# cause unexpected behavior in queries and admin interfaces.
#
# STATE CHANGES CAPTURED (commented out to show what Django detected):
#
# migrations.AlterModelOptions(
#     name='projectsettings',
#     options={
#         'get_latest_by': '-created_at',
#         'ordering': ['created_at'],
#         'verbose_name_plural': 'project settings'
#     },
# ),

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0028_site_elevation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelOptions(
                    name='projectsettings',
                    options={'get_latest_by': '-created_at', 'ordering': ['created_at'], 'verbose_name_plural': 'project settings'},
                ),
            ],
            database_operations=[
                # Meta options don't affect database schema, so no database changes needed
                migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
            ],
        ),
    ]
