# Generated by Django 5.2.7 on 2025-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0029_alter_projectsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='export_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='export_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
