# Generated by Django 5.2.7 on 2026-05-19 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0030_sitepushhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='site',
            name='site_must_be_owned_once',
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner to which the site belongs'),
        ),
        migrations.AlterField(
            model_name='sitenote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author of the note'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', True), ('owner__isnull', True), _connector='OR'), name='site_owned_by_at_most_one'),
        ),
    ]
