# Generated by Django 5.2.7 on 2026-06-04 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0031_remove_site_site_must_be_owned_once_alter_site_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='settings',
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner to which the site belongs'),
        ),
        migrations.DeleteModel(
            name='ProjectSettings',
        ),
    ]
