# Generated by Django 5.2.7 on 2026-07-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0032_remove_project_settings_alter_site_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenote',
            name='saved_author',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
