# Generated by Django 5.2.7 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0033_sitenote_saved_author'),
    ]

    # 0031 relaxed the constraint from XOR to at-most-one so
    # `Site.owner = SET_NULL` could produce orphan sites (both owner and
    # project null). We then overrode that FK back to CASCADE (see 0032),
    # so orphans are no longer produced by any runtime path. Restore the
    # tighter XOR invariant so `Site.is_unaffiliated` (owner is not None)
    # and callers that infer "affiliated ⇒ has project" stay sound.
    operations = [
        migrations.RemoveConstraint(
            model_name='site',
            name='site_owned_by_at_most_one',
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(project__isnull=False) | models.Q(owner__isnull=False))
                    & (models.Q(project__isnull=True) | models.Q(owner__isnull=True))
                ),
                name='site_must_be_owned_once',
            ),
        ),
    ]
